resources:
  - name: example_dbp_repo
    type: GitRepo
    configuration:
      gitProvider: manishas_github   # replace with your integration
      path: manishas-jfrog/example-docker-build-push    # replace with your repository name
      branches:
        include: master

  - name: build_info_dbp
    type: BuildInfo
    configuration:
      sourceArtifactory: demoArt
      buildName: svc_build
      buildNumber: 1

  - name: promoted_build_info_dbp
    type: BuildInfo
    configuration:
      sourceArtifactory: demoArt
      buildName: svc_build
      buildNumber: 1

pipelines:
  - name: example_docker_build_push_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: pipe-master.jfrog.info:8082/docker-local/alpine37
          dockerImageTag: ${run_number}
          inputResources:
            - name: example_dbp_repo
          integrations:
            - name: demoArt

      - name: docker_push
        type: DockerPush
        configuration:
          targetRepository: docker-local
          integrations:
            - name: demoArt
          inputSteps:
            - name: docker_build

      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: build_info_dbp

      - name: promote_build
        type: PromoteBuild
        configuration:
          targetRepository: promoted-pipelines
          integrations:
            - name: demoArt
          inputResources:
            - name: build_info_dbp
          outputResources:
            - name: promoted_build_info_dbp
